---
- hosts: los_docker
  become: true
  tasks:
    - name: Copia WAR remotamente al Servidor Docker
      copy:
        src: /home/ansibleadmin/carpeta_de_wars/rihanna.war
        dest: /home/dockeradmin/contenedores-rihanna/
